// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHiwPDfqDvTRoa7iyocqoH2T9J_zB20bk',
    appId: '1:160289552483:web:0474943069df4123cca056',
    messagingSenderId: '160289552483',
    projectId: 'projects-aca8f',
    authDomain: 'projects-aca8f.firebaseapp.com',
    storageBucket: 'projects-aca8f.appspot.com',
    measurementId: 'G-HS9Z5X5MTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwcsJPCuslbbZsm63Q0R33V2rYHrmOeRY',
    appId: '1:160289552483:android:e56ecfe3a8f42042cca056',
    messagingSenderId: '160289552483',
    projectId: 'projects-aca8f',
    storageBucket: 'projects-aca8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApP63UncClE-Pa3uagsMrZX3WkuFdp6M8',
    appId: '1:160289552483:ios:d9a59cacbcf99504cca056',
    messagingSenderId: '160289552483',
    projectId: 'projects-aca8f',
    storageBucket: 'projects-aca8f.appspot.com',
    iosBundleId: 'com.example.gitbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApP63UncClE-Pa3uagsMrZX3WkuFdp6M8',
    appId: '1:160289552483:ios:77729c53ea310287cca056',
    messagingSenderId: '160289552483',
    projectId: 'projects-aca8f',
    storageBucket: 'projects-aca8f.appspot.com',
    iosBundleId: 'com.example.gitbit.RunnerTests',
  );
}
